### ISSUE TITLE
Version number mismatch on github and npm directory

### ISSUE THREAD

**Issue by martinjuhasz** [inxilpro/node-app-root-path#12]
The [npm directory still lists version 1.0.0](https://www.npmjs.com/package/app-root-path) as the latest version while your package.json claims the package is on 1.2.0.

Did you miss to run `npm publish` after updating the version? Would really appreciate an update, since it causes minor version mismatches in my project.

Thanks for this, anyway!

**Comment by inxilpro** [comment]
Yeah, version numbering got messed up. 1.0.0 is the current release.  The next version should address an Electron issue, but that's it.
