### ISSUE TITLE
npm published version != package.json version

### ISSUE THREAD

**Issue by massa84** [inxilpro/node-app-root-path#14]
There is an issue with the current published version of app-root-path.

my package.json contains
```json
"dependencies": {
    "app-root-path": "^1.0.0"
}
```

but if i run `npm outdated` I get 
```
Package        Current  Wanted  Latest
app-root-path    1.0.0   1.2.0   1.0.0
```

if 1.2.0 is a beta that it should have been published as `1.2.0-beta`

**Comment by pickhardt** [comment]
I noticed this too.

If you're curious what you're missing out on:

1.1.0 added a fix for CLI libaries https://github.com/inxilpro/node-app-root-path/issues/8

1.2.0 added a fix for when running inside an Electron renderer process https://github.com/inxilpro/node-app-root-path/commit/9eb0173dd138280e027fd2b5afb687bd8ed94b43

**Comment by inxilpro** [comment]
Fixed.
