### ISSUE TITLE
Not returning the correct app path on AWS Lambda

### ISSUE THREAD

**Issue by motocombotag** [inxilpro/node-app-root-path#23]
Fix it please. It wasted 2 days of my time.

**Comment by inxilpro** [comment]
Hm. I can try to help, but you’re going to need to provide a little more detail, and maybe try asking in a less entitled way. No one forced you to use my free, open source library. Most open source maintainers would probably just close an issue like this without any response.

**Comment by motocombotag** [comment]
You're right. I apologize. I was _that much_ frustrated. I didn't use your library directly - it was used by `phantomjs` which I used in a project and after some time-wasting, I realized that the path that is logged on AWS Lambda is `/var/runtime/awslambda` or something like that, while the actual Lambda function runs in `/var/task`.

**Comment by jrtipton** [comment]
if (process.env.LAMBDA_TASK_ROOT && process.env.AWS_EXECUTION_ENV) {
    return process.env.LAMBDA_TASK_ROOT;
  }

...is one way to fix it

**Comment by inxilpro** [comment]
Fixed by #24
