### ISSUE TITLE
How would I use this in ES6 syntax (import)?

### ISSUE THREAD

**Issue by NetOperatorWibby** [inxilpro/node-app-root-path#25]
I like `const reqlib = require('app-root-path').require;` but I would love to use this with `import`. How would I go about doing this?

**Comment by inxilpro** [comment]
This should work:

```js
import { require as reqlib } from "app-root-path";
reqlib('foo');
```

**Comment by NetOperatorWibby** [comment]
Sweet, thanks man! :D
