### ISSUE TITLE
Rest resolve parameter.

### ISSUE THREAD

**Issue by filenwind** [inxilpro/node-app-root-path#26]
If rest appRootPath.resolve params and join with path.sep will be great.

```js
var appRootPath = require('app-roo-path');
var barDirPath = appRootPath.resolve('foo', 'bar'); //  root/foo/bar
```

**Comment by inxilpro** [comment]
I don't plan on expanding the scope of the package. If I release a 3.0, it will probably *only* export the path and nothing else.
