### ISSUE TITLE
Version 2.1.0 Broken

### ISSUE THREAD

**Issue by simlu** [inxilpro/node-app-root-path#27]
No longer works correctly inside docker container (using amazon linux)

It now points to `/var/task/` instead of correct folder (was `/user/project/`)

Let me know if you need help reproducing.

**Comment by MacMcIrish** [comment]
Seeing the same thing.

We're using [lambci](https://github.com/lambci/docker-lambda) build container. So app root path now detects it incorrectly as a lambda function.

**Comment by inxilpro** [comment]
Can you re-open with steps to reproduce if 2.2.1 didn't solve this?

**Comment by simlu** [comment]
We fixed it by overwriting the env var. So this was solved
