### ISSUE TITLE
Webpack warning: Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by nickforddesign** [inxilpro/node-app-root-path#30]
https://github.com/webpack/webpack/issues/196

```shell
in ./node_modules/app-root-path/browser-shim.js
Critical dependency: the request of a dependency is an expression
```
It's not a catastrophic error but it is pretty unfortunate having to filter this error in all of my webpack projects that use it.

**Comment by PaulTondeur** [comment]
Would be good if this issue could be resolved.

**Comment by inxilpro** [comment]
Can y'all give me more details or steps to reproduce?

**Comment by d-pollard** [comment]
@inxilpro if you use the `vue-cli` to create a new app: `vue create some-app` then install this repo, import it in a file and you'll see the error specified

**Comment by inxilpro** [comment]
Version 2.2.0 should address this issue, although this package really doesn't make sense in the context of webpack, so it might be better to remove the browser-shim altogether down the road.
