### ISSUE TITLE
Main lib returns object, not path string

### ISSUE THREAD

**Issue by mhkeller** [inxilpro/node-app-root-path#7]
The docs should be updated to reflect that `require('app-root-path')` returns an object, not the path string. It should be `.require('app-root-path').path`.

https://github.com/inxilpro/node-app-root-path/blob/master/lib/app-root-path.js#L37

**Comment by inxilpro** [comment]
You actually don't have to use `.path` because the object provides a `toString()` method.  So if you use the object like a string, it will behave like a string.

That said, it might not hurt to document that quirk.

**Comment by inxilpro** [comment]
The `README.md` has been updated.  Thanks!
