### ISSUE TITLE
Incorrect root path when using with cli libraries

### ISSUE THREAD

**Issue by olsonpm** [inxilpro/node-app-root-path#8]
Example repository which exhibits the behavior

https://github.com/olsonpm/exampleCLI

```
$ npm install --save -g "olsonpm/exampleCLI"
... # let it install
$ exampleCLI
# outputs
root
{ resolve: [Function],
  require: [Function],
  toString: [Function],
  setPath: [Function],
  path: '/home/<username>/.nvm/v0.10.36/lib/node_modules/exampleCLI/bin' }

root.toString()
/home/<username>/.nvm/v0.10.36/lib/node_modules/exampleCLI/bin
```

Now based on the readme (and without digging into your code), I couldn't tell if it should be reporting
/home/<username>/.nvm/v0.10.36/lib
or
/home/<username>/.nvm/v0.10.36/lib/node_modules/exampleCLI

however I didn't expect it to report the bin directory

**Comment by inxilpro** [comment]
Hmm, this is an interesting issue.  Arguably, it should return `/home/<username>/.nvm/v0.10.36/lib/node_modules/exampleCLI/` without the `bin/` component.  The reason you're not getting `/home/<username>/.nvm/v0.10.36/lib/` is because you're dealing with a node global path.

Interesting.  Let me give it a bit of thought.  This is another example of how many freaking edge cases there are where it's hard to say what the "root path" actually is :)

**Comment by zero5100** [comment]
I am currently experiencing this issue as well. I created and installed a global npm module that has a cli command, and app-root-path reports the <appRootDir>/bin directory as the path.

**Comment by inxilpro** [comment]
Hrm, seems like maybe there needs to be custom logic for `bin/` (and `/.bin` perhaps).  It seems like unless your module is called "bin" it should be fine, and this is common npm functionality…

**Comment by zero5100** [comment]
Yeah...if you are naming your project "bin" you are just asking for things to break.

**Comment by inxilpro** [comment]
@zero5100 are you using nvm as well?

**Comment by zero5100** [comment]
@inxilpro Yes, I am.

**Comment by inxilpro** [comment]
The latest commits should fix this. Sorry it took so long. You can try it with:

`npm i -S app-root-path@beta`

I'll publish as `1.1.0` shortly after a little more testing.

**Comment by olsonpm** [comment]
Not a problem - and thanks much!

**Comment by inxilpro** [comment]
Would you mind confirming that the fix works as expected?

**Comment by olsonpm** [comment]
I'm busy tonight but will get to it tomorrow.

**Comment by inxilpro** [comment]
Of course! Whenever you have time…

**Comment by olsonpm** [comment]
Got around to it just now - works as expected.

woot

**Comment by rockymadden** [comment]
Experiencing this same issue but with `src` where the project is a CLI whose index lives at `./src/index.js`.
